In [4]:
from fpl import db
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

from fpl.config import RECENCY_DECAY_RATE, STATS_LOOKBACK_DAYS

shots_df = db.read_table("understat_shots")
fixtures_df = db.read_table("understat_fixtures")
fixtures_df["date"] = pd.to_datetime(fixtures_df["date"])

lookback_start = datetime.now() - timedelta(days=STATS_LOOKBACK_DAYS)
fixtures_df = fixtures_df[fixtures_df["date"] >= lookback_start]

shots_df = shots_df.merge(fixtures_df[["match_id", "date"]], on="match_id")
shots_df["days_ago"] = (datetime.now() - shots_df["date"]).dt.days
# shots_df["weight"] = np.exp(-RECENCY_DECAY_RATE * shots_df["days_ago"])
shots_df["weight"] = np.exp(-0.00001 * shots_df["days_ago"])
shots_df["mins_passed_weighted"] = shots_df["mins_passed"] * shots_df["weight"]
shots_df["xg_weighted"] = shots_df["xg"] * shots_df["weight"]

In [5]:
shots_df[shots_df['match_id'] == 31194]

,id,match_id,minute,result,xg,h_a,h_team,a_team,player,player_id,...,opp_team_gamestate,shot_num,shotontarget_num,goal,competition,date,days_ago,weight,mins_passed_weighted,xg_weighted
9753,30510,31194,0,MissedShots,0.063580,a,Tottenham,Newcastle United,Anthony Elanga,9524.0,...,Draw,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,0.0,0.063580
9754,30511,31194,8,MissedShots,0.055011,a,Tottenham,Newcastle United,Harvey Barnes,6681.0,...,Draw,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,8.0,0.055011
9755,30512,31194,14,SavedShot,0.047796,h,Tottenham,Newcastle United,Mathys Tel,9780.0,...,Draw,1,1,0,EPL,2026-08-29 16:30:00,0,1.0,14.0,0.047796
9756,30513,31194,16,MissedShots,0.061446,h,Tottenham,Newcastle United,Sandro Tonali,7958.0,...,Draw,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,2.0,0.061446
9757,30514,31194,16,BlockedShot,0.128653,h,Tottenham,Newcastle United,Pedro Porro,6912.0,...,Draw,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,0.0,0.128653
9758,30515,31194,21,MissedShots,0.023290,h,Tottenham,Newcastle United,Pedro Porro,6912.0,...,Draw,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,5.0,0.023290
9759,30516,31194,23,MissedShots,0.040308,a,Tottenham,Newcastle United,Joe Willock,6630.0,...,Draw,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,15.0,0.040308
9760,30517,31194,32,MissedShots,0.035340,h,Tottenham,Newcastle United,Omar Marmoush,8393.0,...,Draw,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,11.0,0.035340
9761,30518,31194,32,MissedShots,0.056488,a,Tottenham,Newcastle United,Joe Willock,6630.0,...,Draw,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,9.0,0.056488
9762,30519,31194,33,MissedShots,0.115092,a,Tottenham,Newcastle United,Yoane Wissa,5786.0,...,Draw,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,1.0,0.115092
9763,30520,31194,35,SavedShot,0.063732,h,Tottenham,Newcastle United,Andrew Robertson,1688.0,...,Draw,1,1,0,EPL,2026-08-29 16:30:00,0,1.0,3.0,0.063732
9764,30521,31194,36,SavedShot,0.297928,h,Tottenham,Newcastle United,Jan Paul van Hecke,10807.0,...,Draw,1,1,0,EPL,2026-08-29 16:30:00,0,1.0,1.0,0.297928
9765,30522,31194,43,BlockedShot,0.033269,h,Tottenham,Newcastle United,Pedro Porro,6912.0,...,Draw,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,7.0,0.033269
9766,30523,31194,48,MissedShots,0.056393,a,Tottenham,Newcastle United,Lewis Hall,10216.0,...,Draw,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,15.0,0.056393
9767,30524,31194,49,BlockedShot,0.048912,h,Tottenham,Newcastle United,Mathys Tel,9780.0,...,Draw,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,6.0,0.048912
9768,30525,31194,54,BlockedShot,0.014679,a,Tottenham,Newcastle United,Sven Botman,8635.0,...,Draw,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,6.0,0.014679
9769,30526,31194,59,MissedShots,0.010826,h,Tottenham,Newcastle United,Omar Marmoush,8393.0,...,Draw,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,10.0,0.010826
9770,30527,31194,60,MissedShots,0.013619,a,Tottenham,Newcastle United,Joe Willock,6630.0,...,Draw,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,6.0,0.013619
9771,30528,31194,61,Goal,0.077577,a,Tottenham,Newcastle United,Anthony Elanga,9524.0,...,Draw,1,1,1,EPL,2026-08-29 16:30:00,0,1.0,1.0,0.077577
9772,30529,31194,66,MissedShots,0.074677,h,Tottenham,Newcastle United,Mathys Tel,9780.0,...,Winning,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,7.0,0.074677
9773,30530,31194,69,MissedShots,0.021364,h,Tottenham,Newcastle United,Pedro Porro,6912.0,...,Winning,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,3.0,0.021364
9774,30531,31194,70,MissedShots,0.018845,h,Tottenham,Newcastle United,Mateus Fernandes,12948.0,...,Winning,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,1.0,0.018845
9775,30532,31194,71,Goal,0.507455,a,Tottenham,Newcastle United,Yoane Wissa,5786.0,...,Losing,1,1,1,EPL,2026-08-29 16:30:00,0,1.0,10.0,0.507455
9776,30533,31194,71,BlockedShot,0.018908,a,Tottenham,Newcastle United,Nick Woltemade,8117.0,...,Losing,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,0.0,0.018908
9777,30534,31194,84,MissedShots,0.017168,h,Tottenham,Newcastle United,Mikey Moore,12603.0,...,Winning,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,14.0,0.017168
9778,30535,31194,86,SavedShot,0.062881,h,Tottenham,Newcastle United,Omar Marmoush,8393.0,...,Winning,1,1,0,EPL,2026-08-29 16:30:00,0,1.0,2.0,0.062881
9779,30536,31194,87,BlockedShot,0.054618,h,Tottenham,Newcastle United,Mohammed Kudus,12027.0,...,Winning,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,1.0,0.054618
9780,30537,31194,91,BlockedShot,0.127528,h,Tottenham,Newcastle United,Dominic Solanke,1679.0,...,Winning,1,0,0,EPL,2026-08-29 16:30:00,0,1.0,4.0,0.127528
9781,30538,31194,91,NoShots,0.000000,a,Tottenham,Newcastle United,NaN,NaN,...,Losing,0,0,0,NaN,2026-08-29 16:30:00,0,1.0,19.0,0.000000

In [6]:
shots_df.columns

Index(['id', 'match_id', 'minute', 'result', 'xg', 'h_a', 'h_team', 'a_team',
       'player', 'player_id', 'h_score', 'a_score', 'mins_passed',
       'h_gamestate', 'a_gamestate', 'action_team', 'action_team_gamestate',
       'opp_team', 'opp_team_gamestate', 'shot_num', 'shotontarget_num',
       'goal', 'competition', 'date', 'days_ago', 'weight',
       'mins_passed_weighted', 'xg_weighted'],
      dtype='str')

In [7]:
shots_df[shots_df['match_id'] == 31194][['h_team', 'a_team', 'h_score', 'a_score', 'h_gamestate', 'a_gamestate', 'minute', 'mins_passed', 'result', 'xg', 'h_a', 'action_team', 'action_team_gamestate', 'opp_team', 'opp_team_gamestate']]

,h_team,a_team,h_score,a_score,h_gamestate,a_gamestate,minute,mins_passed,result,xg,h_a,action_team,action_team_gamestate,opp_team,opp_team_gamestate
9753,Tottenham,Newcastle United,0,0,Draw,Draw,0,0,MissedShots,0.063580,a,Newcastle United,Draw,Tottenham,Draw
9754,Tottenham,Newcastle United,0,0,Draw,Draw,8,8,MissedShots,0.055011,a,Newcastle United,Draw,Tottenham,Draw
9755,Tottenham,Newcastle United,0,0,Draw,Draw,14,14,SavedShot,0.047796,h,Tottenham,Draw,Newcastle United,Draw
9756,Tottenham,Newcastle United,0,0,Draw,Draw,16,2,MissedShots,0.061446,h,Tottenham,Draw,Newcastle United,Draw
9757,Tottenham,Newcastle United,0,0,Draw,Draw,16,0,BlockedShot,0.128653,h,Tottenham,Draw,Newcastle United,Draw
9758,Tottenham,Newcastle United,0,0,Draw,Draw,21,5,MissedShots,0.023290,h,Tottenham,Draw,Newcastle United,Draw
9759,Tottenham,Newcastle United,0,0,Draw,Draw,23,15,MissedShots,0.040308,a,Newcastle United,Draw,Tottenham,Draw
9760,Tottenham,Newcastle United,0,0,Draw,Draw,32,11,MissedShots,0.035340,h,Tottenham,Draw,Newcastle United,Draw
9761,Tottenham,Newcastle United,0,0,Draw,Draw,32,9,MissedShots,0.056488,a,Newcastle United,Draw,Tottenham,Draw
9762,Tottenham,Newcastle United,0,0,Draw,Draw,33,1,MissedShots,0.115092,a,Newcastle United,Draw,Tottenham,Draw
9763,Tottenham,Newcastle United,0,0,Draw,Draw,35,3,SavedShot,0.063732,h,Tottenham,Draw,Newcastle United,Draw
9764,Tottenham,Newcastle United,0,0,Draw,Draw,36,1,SavedShot,0.297928,h,Tottenham,Draw,Newcastle United,Draw
9765,Tottenham,Newcastle United,0,0,Draw,Draw,43,7,BlockedShot,0.033269,h,Tottenham,Draw,Newcastle United,Draw
9766,Tottenham,Newcastle United,0,0,Draw,Draw,48,15,MissedShots,0.056393,a,Newcastle United,Draw,Tottenham,Draw
9767,Tottenham,Newcastle United,0,0,Draw,Draw,49,6,BlockedShot,0.048912,h,Tottenham,Draw,Newcastle United,Draw
9768,Tottenham,Newcastle United,0,0,Draw,Draw,54,6,BlockedShot,0.014679,a,Newcastle United,Draw,Tottenham,Draw
9769,Tottenham,Newcastle United,0,0,Draw,Draw,59,10,MissedShots,0.010826,h,Tottenham,Draw,Newcastle United,Draw
9770,Tottenham,Newcastle United,0,0,Draw,Draw,60,6,MissedShots,0.013619,a,Newcastle United,Draw,Tottenham,Draw
9771,Tottenham,Newcastle United,0,0,Draw,Draw,61,1,Goal,0.077577,a,Newcastle United,Draw,Tottenham,Draw
9772,Tottenham,Newcastle United,0,1,Losing,Winning,66,7,MissedShots,0.074677,h,Tottenham,Losing,Newcastle United,Winning
9773,Tottenham,Newcastle United,0,1,Losing,Winning,69,3,MissedShots,0.021364,h,Tottenham,Losing,Newcastle United,Winning
9774,Tottenham,Newcastle United,0,1,Losing,Winning,70,1,MissedShots,0.018845,h,Tottenham,Losing,Newcastle United,Winning
9775,Tottenham,Newcastle United,0,1,Losing,Winning,71,10,Goal,0.507455,a,Newcastle United,Winning,Tottenham,Losing
9776,Tottenham,Newcastle United,0,2,Losing,Winning,71,0,BlockedShot,0.018908,a,Newcastle United,Winning,Tottenham,Losing
9777,Tottenham,Newcastle United,0,2,Losing,Winning,84,14,MissedShots,0.017168,h,Tottenham,Losing,Newcastle United,Winning
9778,Tottenham,Newcastle United,0,2,Losing,Winning,86,2,SavedShot,0.062881,h,Tottenham,Losing,Newcastle United,Winning
9779,Tottenham,Newcastle United,0,2,Losing,Winning,87,1,BlockedShot,0.054618,h,Tottenham,Losing,Newcastle United,Winning
9780,Tottenham,Newcastle United,0,2,Losing,Winning,91,4,BlockedShot,0.127528,h,Tottenham,Losing,Newcastle United,Winning
9781,Tottenham,Newcastle United,0,2,Losing,Winning,91,19,NoShots,0.000000,a,Newcastle United,Winning,Tottenham,Losing

In [ ]:
# from fpl.scrape.understat import _get_json, _process_shots, _session

# data = _get_json(_session(), f"getMatchData/{31194}")
# shots = [shot for side in data["shots"].values() for shot in side]

# _process_shots(shots, 31194)[['h_team', 'a_team', 'h_score', 'a_score', 'h_gamestate', 'a_gamestate', 'minute', 'mins_passed', 'result', 'xg', 'h_a', 'action_team', 'action_team_gamestate', 'opp_team', 'opp_team_gamestate']]

,h_team,a_team,h_score,a_score,h_gamestate,a_gamestate,minute,mins_passed,result,xg,h_a,action_team,action_team_gamestate,opp_team,opp_team_gamestate
0,Tottenham,Newcastle United,0.0,0.0,Draw,Draw,0,0.0,MissedShots,0.063580,a,Newcastle United,Draw,Tottenham,Draw
1,Tottenham,Newcastle United,0.0,0.0,Draw,Draw,8,8.0,MissedShots,0.055011,a,Newcastle United,Draw,Tottenham,Draw
2,Tottenham,Newcastle United,0.0,0.0,Draw,Draw,14,14.0,SavedShot,0.047796,h,Tottenham,Draw,Newcastle United,Draw
3,Tottenham,Newcastle United,0.0,0.0,Draw,Draw,16,2.0,MissedShots,0.061446,h,Tottenham,Draw,Newcastle United,Draw
4,Tottenham,Newcastle United,0.0,0.0,Draw,Draw,16,0.0,BlockedShot,0.128653,h,Tottenham,Draw,Newcastle United,Draw
5,Tottenham,Newcastle United,0.0,0.0,Draw,Draw,21,5.0,MissedShots,0.023290,h,Tottenham,Draw,Newcastle United,Draw
6,Tottenham,Newcastle United,0.0,0.0,Draw,Draw,23,15.0,MissedShots,0.040308,a,Newcastle United,Draw,Tottenham,Draw
7,Tottenham,Newcastle United,0.0,0.0,Draw,Draw,32,11.0,MissedShots,0.035340,h,Tottenham,Draw,Newcastle United,Draw
8,Tottenham,Newcastle United,0.0,0.0,Draw,Draw,32,9.0,MissedShots,0.056488,a,Newcastle United,Draw,Tottenham,Draw
9,Tottenham,Newcastle United,0.0,0.0,Draw,Draw,33,1.0,MissedShots,0.115092,a,Newcastle United,Draw,Tottenham,Draw
10,Tottenham,Newcastle United,0.0,0.0,Draw,Draw,35,3.0,SavedShot,0.063732,h,Tottenham,Draw,Newcastle United,Draw
11,Tottenham,Newcastle United,0.0,0.0,Draw,Draw,36,1.0,SavedShot,0.297928,h,Tottenham,Draw,Newcastle United,Draw
12,Tottenham,Newcastle United,0.0,0.0,Draw,Draw,43,7.0,BlockedShot,0.033269,h,Tottenham,Draw,Newcastle United,Draw
13,Tottenham,Newcastle United,0.0,0.0,Draw,Draw,48,15.0,MissedShots,0.056393,a,Newcastle United,Draw,Tottenham,Draw
14,Tottenham,Newcastle United,0.0,0.0,Draw,Draw,49,6.0,BlockedShot,0.048912,h,Tottenham,Draw,Newcastle United,Draw
15,Tottenham,Newcastle United,0.0,0.0,Draw,Draw,54,6.0,BlockedShot,0.014679,a,Newcastle United,Draw,Tottenham,Draw
16,Tottenham,Newcastle United,0.0,0.0,Draw,Draw,59,10.0,MissedShots,0.010826,h,Tottenham,Draw,Newcastle United,Draw
17,Tottenham,Newcastle United,0.0,0.0,Draw,Draw,60,6.0,MissedShots,0.013619,a,Newcastle United,Draw,Tottenham,Draw
18,Tottenham,Newcastle United,0.0,0.0,Draw,Draw,61,1.0,Goal,0.077577,a,Newcastle United,Draw,Tottenham,Draw
19,Tottenham,Newcastle United,0.0,1.0,Losing,Winning,66,7.0,MissedShots,0.074677,h,Tottenham,Losing,Newcastle United,Winning
20,Tottenham,Newcastle United,0.0,1.0,Losing,Winning,69,3.0,MissedShots,0.021364,h,Tottenham,Losing,Newcastle United,Winning
21,Tottenham,Newcastle United,0.0,1.0,Losing,Winning,70,1.0,MissedShots,0.018845,h,Tottenham,Losing,Newcastle United,Winning
22,Tottenham,Newcastle United,0.0,1.0,Losing,Winning,71,10.0,Goal,0.507455,a,Newcastle United,Winning,Tottenham,Losing
23,Tottenham,Newcastle United,0.0,2.0,Losing,Winning,71,0.0,BlockedShot,0.018908,a,Newcastle United,Winning,Tottenham,Losing
24,Tottenham,Newcastle United,0.0,2.0,Losing,Winning,84,14.0,MissedShots,0.017168,h,Tottenham,Losing,Newcastle United,Winning
25,Tottenham,Newcastle United,0.0,2.0,Losing,Winning,86,2.0,SavedShot,0.062881,h,Tottenham,Losing,Newcastle United,Winning
26,Tottenham,Newcastle United,0.0,2.0,Losing,Winning,87,1.0,BlockedShot,0.054618,h,Tottenham,Losing,Newcastle United,Winning
27,Tottenham,Newcastle United,0.0,2.0,Losing,Winning,91,4.0,BlockedShot,0.127528,h,Tottenham,Losing,Newcastle United,Winning
28,Tottenham,Newcastle United,0.0,2.0,Losing,Winning,91,19.0,NoShots,0.000000,a,Newcastle United,Winning,Tottenham,Losing

In [15]:
h_shots_df = shots_df[shots_df["h_a"] == "h"]

print(h_shots_df['xg'].sum() / h_shots_df['mins_passed'].sum())
print(h_shots_df['xg'].sum() / h_shots_df['match_id'].unique().size / 90)

print(h_shots_df['match_id'].unique().size * 90)

print(shots_df['mins_passed'].sum()/2)

print(shots_df['mins_passed'].sum()/2 / shots_df['match_id'].unique().size)

print(h_shots_df['xg'].sum() / h_shots_df['match_id'].unique().size)

0.018808550773728942
0.019348007874439153
33750
34638.5
92.36933333333333
1.7413207086995237

In [16]:
team_col = "action_team"
gamestate_col = "action_team_gamestate"
metric = "xg"

grouped = shots_df.pivot_table(
        values=["mins_passed_weighted", "xg_weighted", "weight"],
        index=[team_col, "h_a", gamestate_col],
        aggfunc="sum",
    )
grouped[f"{metric}_min"] = grouped["xg_weighted"] / grouped["mins_passed_weighted"]
grouped = grouped.rename_axis(index={team_col: "team", gamestate_col: "gamestate"}).reset_index()

grouped

,team,h_a,gamestate,mins_passed_weighted,weight,xg_weighted,xg_min
0,Arsenal,a,Draw,906.899420,131.694288,19.303107,0.021285
1,Arsenal,a,Losing,201.448032,29.915885,4.886532,0.024257
2,Arsenal,a,Winning,557.787806,77.830110,13.018544,0.023340
3,Arsenal,h,Draw,679.497049,132.712853,15.564030,0.022905
4,Arsenal,h,Losing,200.493954,29.927020,3.782945,0.018868
...,...,...,...,...,...,...,...
125,Wolverhampton Wanderers,a,Losing,995.689959,99.771934,6.195426,0.006222
126,Wolverhampton Wanderers,a,Winning,49.903827,7.987474,1.243431,0.024917
127,Wolverhampton Wanderers,h,Draw,734.479719,72.849688,8.900525,0.012118
128,Wolverhampton Wanderers,h,Losing,746.111800,93.767698,10.461878,0.014022
129,Wolverhampton Wanderers,h,Winning,183.542472,21.947297,2.755835,0.015015

In [ ]:
# Clear understat data from the database to re-populate
# from fpl.db import get_connection

# with get_connection() as conn:
#     cursor = conn.cursor()
#     cursor.execute("DELETE FROM understat_player_stats")
#     cursor.execute("DELETE FROM understat_rosters")
#     cursor.execute("DELETE FROM understat_shots")
#     cursor.execute("DELETE FROM understat_fixtures")
    
    
    
#     conn.commit()

In [3]:
from fpl.scrape.understat import scrape_new_fixtures

scrape_new_fixtures(2025)
scrape_new_fixtures(2026)

Scraping 1/380: Liverpool - Bournemouth
Scraping 2/380: Aston Villa - Newcastle United
Scraping 3/380: Brighton - Fulham
Scraping 4/380: Sunderland - West Ham
Scraping 5/380: Tottenham - Burnley
Scraping 6/380: Wolverhampton Wanderers - Manchester City
Scraping 7/380: Chelsea - Crystal Palace
Scraping 8/380: Nottingham Forest - Brentford
Scraping 9/380: Manchester United - Arsenal
Scraping 10/380: Leeds - Everton
Scraping 11/380: West Ham - Chelsea
Scraping 12/380: Manchester City - Tottenham
Scraping 13/380: Brentford - Aston Villa
Scraping 14/380: Burnley - Sunderland
Scraping 15/380: Bournemouth - Wolverhampton Wanderers
Scraping 16/380: Arsenal - Leeds
Scraping 17/380: Crystal Palace - Nottingham Forest
Scraping 18/380: Everton - Brighton
Scraping 19/380: Fulham - Manchester United
Scraping 20/380: Newcastle United - Liverpool
Scraping 21/380: Chelsea - Fulham
Scraping 22/380: Tottenham - Bournemouth
Scraping 23/380: Wolverhampton Wanderers - Everton
Scraping 24/380: Sunderland - Brentford
Scraping 25/380: Manchester United - Burnley
Scraping 26/380: Leeds - Newcastle United
Scraping 27/380: Nottingham Forest - West Ham
Scraping 28/380: Brighton - Manchester City
Scraping 29/380: Liverpool - Arsenal
Scraping 30/380: Aston Villa - Crystal Palace
Scraping 31/380: Arsenal - Nottingham Forest
Scraping 32/380: Newcastle United - Wolverhampton Wanderers
Scraping 33/380: Bournemouth - Brighton
Scraping 34/380: Crystal Palace - Sunderland
Scraping 35/380: Everton - Aston Villa
Scraping 36/380: Fulham - Leeds
Scraping 37/380: West Ham - Tottenham
Scraping 38/380: Brentford - Chelsea
Scraping 39/380: Burnley - Liverpool
Scraping 40/380: Manchester City - Manchester United
Scraping 41/380: Liverpool - Everton
Scraping 42/380: West Ham - Crystal Palace
Scraping 43/380: Wolverhampton Wanderers - Leeds
Scraping 44/380: Brighton - Tottenham
Scraping 45/380: Burnley - Nottingham Forest
Scraping 46/380: Manchester United - Chelsea
Scraping 47/380: Fulham - Brentford
Scraping 48/380: Bournemouth - Newcastle United
Scraping 49/380: Sunderland - Aston Villa
Scraping 50/380: Arsenal - Manchester City
Scraping 51/380: Brentford - Manchester United
Scraping 52/380: Chelsea - Brighton
Scraping 53/380: Crystal Palace - Liverpool
Scraping 54/380: Leeds - Bournemouth
Scraping 55/380: Manchester City - Burnley
Scraping 56/380: Nottingham Forest - Sunderland
Scraping 57/380: Tottenham - Wolverhampton Wanderers
Scraping 58/380: Aston Villa - Fulham
Scraping 59/380: Newcastle United - Arsenal
Scraping 60/380: Everton - West Ham
Scraping 61/380: Bournemouth - Fulham
Scraping 62/380: Leeds - Tottenham
Scraping 63/380: Arsenal - West Ham
Scraping 64/380: Manchester United - Sunderland
Scraping 65/380: Chelsea - Liverpool
Scraping 66/380: Aston Villa - Burnley
Scraping 67/380: Everton - Crystal Palace
Scraping 68/380: Newcastle United - Nottingham Forest
Scraping 69/380: Wolverhampton Wanderers - Brighton
Scraping 70/380: Brentford - Manchester City
Scraping 71/380: Nottingham Forest - Chelsea
Scraping 72/380: Brighton - Newcastle United
Scraping 73/380: Burnley - Leeds
Scraping 74/380: Crystal Palace - Bournemouth
Scraping 75/380: Manchester City - Everton
Scraping 76/380: Sunderland - Wolverhampton Wanderers
Scraping 77/380: Fulham - Arsenal
Scraping 78/380: Tottenham - Aston Villa
Scraping 79/380: Liverpool - Manchester United
Scraping 80/380: West Ham - Brentford
Scraping 81/380: Leeds - West Ham
Scraping 82/380: Chelsea - Sunderland
Scraping 83/380: Newcastle United - Fulham
Scraping 84/380: Manchester United - Brighton
Scraping 85/380: Brentford - Liverpool
Scraping 86/380: Bournemouth - Nottingham Forest
Scraping 87/380: Arsenal - Crystal Palace
Scraping 88/380: Aston Villa - Manchester City
Scraping 89/380: Wolverhampton Wanderers - Burnley
Scraping 90/380: Everton - Tottenham
Scraping 91/380: Brighton - Leeds
Scraping 92/380: Burnley - Arsenal
Scraping 93/380: Crystal Palace - Brentford
Scraping 94/380: Fulham - Wolverhampton Wanderers
Scraping 95/380: Nottingham Forest - Manchester United
Scraping 96/380: Tottenham - Chelsea
Scraping 97/380: Liverpool - Aston Villa
Scraping 98/380: West Ham - Newcastle United
Scraping 99/380: Manchester City - Bournemouth
Scraping 100/380: Sunderland - Everton
Scraping 101/380: Tottenham - Manchester United
Scraping 102/380: Everton - Fulham
Scraping 103/380: West Ham - Burnley
Scraping 104/380: Sunderland - Arsenal
Scraping 105/380: Chelsea - Wolverhampton Wanderers
Scraping 106/380: Aston Villa - Bournemouth
Scraping 107/380: Brentford - Newcastle United
Scraping 108/380: Crystal Palace - Brighton
Scraping 109/380: Nottingham Forest - Leeds
Scraping 110/380: Manchester City - Liverpool
Scraping 111/380: Burnley - Chelsea
Scraping 112/380: Bournemouth - West Ham
Scraping 113/380: Brighton - Brentford
Scraping 114/380: Fulham - Sunderland
Scraping 115/380: Liverpool - Nottingham Forest
Scraping 116/380: Wolverhampton Wanderers - Crystal Palace
Scraping 117/380: Newcastle United - Manchester City
Scraping 118/380: Leeds - Aston Villa
Scraping 119/380: Arsenal - Tottenham
Scraping 120/380: Manchester United - Everton
Scraping 121/380: Brentford - Burnley
Scraping 122/380: Manchester City - Leeds
Scraping 123/380: Sunderland - Bournemouth
Scraping 124/380: Everton - Newcastle United
Scraping 125/380: Tottenham - Fulham
Scraping 126/380: Crystal Palace - Manchester United
Scraping 127/380: Aston Villa - Wolverhampton Wanderers
Scraping 128/380: Nottingham Forest - Brighton
Scraping 129/380: West Ham - Liverpool
Scraping 130/380: Chelsea - Arsenal
Scraping 131/380: Bournemouth - Everton
Scraping 132/380: Fulham - Manchester City
Scraping 133/380: Newcastle United - Tottenham
Scraping 134/380: Arsenal - Brentford
Scraping 135/380: Brighton - Aston Villa
Scraping 136/380: Burnley - Crystal Palace
Scraping 137/380: Wolverhampton Wanderers - Nottingham Forest
Scraping 138/380: Leeds - Chelsea
Scraping 139/380: Liverpool - Sunderland
Scraping 140/380: Manchester United - West Ham
Scraping 141/380: Aston Villa - Arsenal
Scraping 142/380: Bournemouth - Chelsea
Scraping 143/380: Everton - Nottingham Forest
Scraping 144/380: Manchester City - Sunderland
Scraping 145/380: Newcastle United - Burnley
Scraping 146/380: Tottenham - Brentford
Scraping 147/380: Leeds - Liverpool
Scraping 148/380: Brighton - West Ham
Scraping 149/380: Fulham - Crystal Palace
Scraping 150/380: Wolverhampton Wanderers - Manchester United
Scraping 151/380: Chelsea - Everton
Scraping 152/380: Liverpool - Brighton
Scraping 153/380: Burnley - Fulham
Scraping 154/380: Arsenal - Wolverhampton Wanderers
Scraping 155/380: Crystal Palace - Manchester City
Scraping 156/380: Nottingham Forest - Tottenham
Scraping 157/380: Sunderland - Newcastle United
Scraping 158/380: West Ham - Aston Villa
Scraping 159/380: Brentford - Leeds
Scraping 160/380: Manchester United - Bournemouth
Scraping 161/380: Newcastle United - Chelsea
Scraping 162/380: Bournemouth - Burnley
Scraping 163/380: Brighton - Sunderland
Scraping 164/380: Manchester City - West Ham
Scraping 165/380: Wolverhampton Wanderers - Brentford
Scraping 166/380: Tottenham - Liverpool
Scraping 167/380: Everton - Arsenal
Scraping 168/380: Leeds - Crystal Palace
Scraping 169/380: Aston Villa - Manchester United
Scraping 170/380: Fulham - Nottingham Forest
Scraping 171/380: Manchester United - Newcastle United
Scraping 172/380: Nottingham Forest - Manchester City
Scraping 173/380: Arsenal - Brighton
Scraping 174/380: Brentford - Bournemouth
Scraping 175/380: Burnley - Everton
Scraping 176/380: Liverpool - Wolverhampton Wanderers
Scraping 177/380: West Ham - Fulham
Scraping 178/380: Chelsea - Aston Villa
Scraping 179/380: Sunderland - Leeds
Scraping 180/380: Crystal Palace - Tottenham
Scraping 181/380: Burnley - Newcastle United
Scraping 182/380: Chelsea - Bournemouth
Scraping 183/380: Nottingham Forest - Everton
Scraping 184/380: West Ham - Brighton
Scraping 185/380: Arsenal - Aston Villa
Scraping 186/380: Manchester United - Wolverhampton Wanderers
Scraping 187/380: Crystal Palace - Fulham
Scraping 188/380: Liverpool - Leeds
Scraping 189/380: Brentford - Tottenham
Scraping 190/380: Sunderland - Manchester City
Scraping 191/380: Aston Villa - Nottingham Forest
Scraping 192/380: Wolverhampton Wanderers - West Ham
Scraping 193/380: Brighton - Burnley
Scraping 194/380: Bournemouth - Arsenal
Scraping 195/380: Leeds - Manchester United
Scraping 196/380: Newcastle United - Crystal Palace
Scraping 197/380: Tottenham - Sunderland
Scraping 198/380: Everton - Brentford
Scraping 199/380: Fulham - Liverpool
Scraping 200/380: Manchester City - Chelsea
Scraping 201/380: West Ham - Nottingham Forest
Scraping 202/380: Everton - Wolverhampton Wanderers
Scraping 203/380: Bournemouth - Tottenham
Scraping 204/380: Brentford - Sunderland
Scraping 205/380: Crystal Palace - Aston Villa
Scraping 206/380: Fulham - Chelsea
Scraping 207/380: Manchester City - Brighton
Scraping 208/380: Burnley - Manchester United
Scraping 209/380: Newcastle United - Leeds
Scraping 210/380: Arsenal - Liverpool
Scraping 211/380: Manchester United - Manchester City
Scraping 212/380: Chelsea - Brentford
Scraping 213/380: Leeds - Fulham
Scraping 214/380: Liverpool - Burnley
Scraping 215/380: Sunderland - Crystal Palace
Scraping 216/380: Tottenham - West Ham
Scraping 217/380: Nottingham Forest - Arsenal
Scraping 218/380: Wolverhampton Wanderers - Newcastle United
Scraping 219/380: Aston Villa - Everton
Scraping 220/380: Brighton - Bournemouth
Scraping 221/380: West Ham - Sunderland
Scraping 222/380: Burnley - Tottenham
Scraping 223/380: Fulham - Brighton
Scraping 224/380: Manchester City - Wolverhampton Wanderers
Scraping 225/380: Bournemouth - Liverpool
Scraping 226/380: Brentford - Nottingham Forest
Scraping 227/380: Crystal Palace - Chelsea
Scraping 228/380: Newcastle United - Aston Villa
Scraping 229/380: Arsenal - Manchester United
Scraping 230/380: Everton - Leeds
Scraping 231/380: Brighton - Everton
Scraping 232/380: Leeds - Arsenal
Scraping 233/380: Wolverhampton Wanderers - Bournemouth
Scraping 234/380: Chelsea - West Ham
Scraping 235/380: Liverpool - Newcastle United
Scraping 236/380: Aston Villa - Brentford
Scraping 237/380: Manchester United - Fulham
Scraping 238/380: Nottingham Forest - Crystal Palace
Scraping 239/380: Tottenham - Manchester City
Scraping 240/380: Sunderland - Burnley
Scraping 241/380: Leeds - Nottingham Forest
Scraping 242/380: Manchester United - Tottenham
Scraping 243/380: Bournemouth - Aston Villa
Scraping 244/380: Arsenal - Sunderland
Scraping 245/380: Burnley - West Ham
Scraping 246/380: Fulham - Everton
Scraping 247/380: Wolverhampton Wanderers - Chelsea
Scraping 248/380: Newcastle United - Brentford
Scraping 249/380: Brighton - Crystal Palace
Scraping 250/380: Liverpool - Manchester City
Scraping 251/380: Chelsea - Leeds
Scraping 252/380: Everton - Bournemouth
Scraping 253/380: Tottenham - Newcastle United
Scraping 254/380: West Ham - Manchester United
Scraping 255/380: Aston Villa - Brighton
Scraping 256/380: Crystal Palace - Burnley
Scraping 257/380: Manchester City - Fulham
Scraping 258/380: Nottingham Forest - Wolverhampton Wanderers
Scraping 259/380: Sunderland - Liverpool
Scraping 260/380: Brentford - Arsenal
Scraping 261/380: Wolverhampton Wanderers - Arsenal
Scraping 262/380: Aston Villa - Leeds
Scraping 263/380: Brentford - Brighton
Scraping 264/380: Chelsea - Burnley
Scraping 265/380: West Ham - Bournemouth
Scraping 266/380: Manchester City - Newcastle United
Scraping 267/380: Crystal Palace - Wolverhampton Wanderers
Scraping 268/380: Nottingham Forest - Liverpool
Scraping 269/380: Sunderland - Fulham
Scraping 270/380: Tottenham - Arsenal
Scraping 271/380: Everton - Manchester United
Scraping 272/380: Wolverhampton Wanderers - Aston Villa
Scraping 273/380: Bournemouth - Sunderland
Scraping 274/380: Burnley - Brentford
Scraping 275/380: Liverpool - West Ham
Scraping 276/380: Newcastle United - Everton
Scraping 277/380: Leeds - Manchester City
Scraping 278/380: Brighton - Nottingham Forest
Scraping 279/380: Fulham - Tottenham
Scraping 280/380: Manchester United - Crystal Palace
Scraping 281/380: Arsenal - Chelsea
Scraping 282/380: Bournemouth - Brentford
Scraping 283/380: Everton - Burnley
Scraping 284/380: Leeds - Sunderland
Scraping 285/380: Wolverhampton Wanderers - Liverpool
Scraping 286/380: Aston Villa - Chelsea
Scraping 287/380: Brighton - Arsenal
Scraping 288/380: Fulham - West Ham
Scraping 289/380: Manchester City - Nottingham Forest
Scraping 290/380: Newcastle United - Manchester United
Scraping 291/380: Tottenham - Crystal Palace
Scraping 292/380: Burnley - Bournemouth
Scraping 293/380: Sunderland - Brighton
Scraping 294/380: Arsenal - Everton
Scraping 295/380: Chelsea - Newcastle United
Scraping 296/380: West Ham - Manchester City
Scraping 297/380: Crystal Palace - Leeds
Scraping 298/380: Manchester United - Aston Villa
Scraping 299/380: Nottingham Forest - Fulham
Scraping 300/380: Liverpool - Tottenham
Scraping 301/380: Brentford - Wolverhampton Wanderers
Scraping 302/380: Bournemouth - Manchester United
Scraping 303/380: Brighton - Liverpool
Scraping 304/380: Fulham - Burnley
Scraping 305/380: Everton - Chelsea
Scraping 306/380: Leeds - Brentford
Scraping 307/380: Newcastle United - Sunderland
Scraping 308/380: Aston Villa - West Ham
Scraping 309/380: Tottenham - Nottingham Forest
Scraping 310/380: West Ham - Wolverhampton Wanderers
Scraping 311/380: Arsenal - Bournemouth
Scraping 312/380: Brentford - Everton
Scraping 313/380: Burnley - Brighton
Scraping 314/380: Liverpool - Fulham
Scraping 315/380: Nottingham Forest - Aston Villa
Scraping 316/380: Sunderland - Tottenham
Scraping 317/380: Crystal Palace - Newcastle United
Scraping 318/380: Chelsea - Manchester City
Scraping 319/380: Manchester United - Leeds
Scraping 320/380: Brentford - Fulham
Scraping 321/380: Leeds - Wolverhampton Wanderers
Scraping 322/380: Newcastle United - Bournemouth
Scraping 323/380: Tottenham - Brighton
Scraping 324/380: Chelsea - Manchester United
Scraping 325/380: Aston Villa - Sunderland
Scraping 326/380: Everton - Liverpool
Scraping 327/380: Nottingham Forest - Burnley
Scraping 328/380: Manchester City - Arsenal
Scraping 329/380: Crystal Palace - West Ham
Scraping 330/380: Brighton - Chelsea
Scraping 331/380: Bournemouth - Leeds
Scraping 332/380: Burnley - Manchester City
Scraping 333/380: Sunderland - Nottingham Forest
Scraping 334/380: Fulham - Aston Villa
Scraping 335/380: Liverpool - Crystal Palace
Scraping 336/380: West Ham - Everton
Scraping 337/380: Wolverhampton Wanderers - Tottenham
Scraping 338/380: Arsenal - Newcastle United
Scraping 339/380: Manchester United - Brentford
Scraping 340/380: Leeds - Burnley
Scraping 341/380: Brentford - West Ham
Scraping 342/380: Newcastle United - Brighton
Scraping 343/380: Wolverhampton Wanderers - Sunderland
Scraping 344/380: Arsenal - Fulham
Scraping 345/380: Bournemouth - Crystal Palace
Scraping 346/380: Manchester United - Liverpool
Scraping 347/380: Aston Villa - Tottenham
Scraping 348/380: Chelsea - Nottingham Forest
Scraping 349/380: Everton - Manchester City
Scraping 350/380: Liverpool - Chelsea
Scraping 351/380: Brighton - Wolverhampton Wanderers
Scraping 352/380: Fulham - Bournemouth
Scraping 353/380: Sunderland - Manchester United
Scraping 354/380: Manchester City - Brentford
Scraping 355/380: Burnley - Aston Villa
Scraping 356/380: Crystal Palace - Everton
Scraping 357/380: Nottingham Forest - Newcastle United
Scraping 358/380: West Ham - Arsenal
Scraping 359/380: Tottenham - Leeds
Scraping 360/380: Manchester City - Crystal Palace
Scraping 361/380: Aston Villa - Liverpool
Scraping 362/380: Manchester United - Nottingham Forest
Scraping 363/380: Brentford - Crystal Palace
Scraping 364/380: Everton - Sunderland
Scraping 365/380: Leeds - Brighton
Scraping 366/380: Wolverhampton Wanderers - Fulham
Scraping 367/380: Newcastle United - West Ham
Scraping 368/380: Arsenal - Burnley
Scraping 369/380: Bournemouth - Manchester City
Scraping 370/380: Chelsea - Tottenham
Scraping 371/380: Brighton - Manchester United
Scraping 372/380: Burnley - Wolverhampton Wanderers
Scraping 373/380: Crystal Palace - Arsenal
Scraping 374/380: Fulham - Newcastle United
Scraping 375/380: Liverpool - Brentford
Scraping 376/380: Manchester City - Aston Villa
Scraping 377/380: Nottingham Forest - Bournemouth
Scraping 378/380: Sunderland - Chelsea
Scraping 379/380: Tottenham - Everton
Scraping 380/380: West Ham - Leeds
Inserted 380 fixtures
Scraping 1/15: Arsenal - Coventry
Scraping 2/15: Hull - Manchester United
Scraping 3/15: Everton - Crystal Palace
Scraping 4/15: Ipswich - Sunderland
Scraping 5/15: Nottingham Forest - Leeds
Scraping 6/15: Brentford - Tottenham
Scraping 7/15: Brighton - Aston Villa
Scraping 8/15: Manchester City - Bournemouth
Scraping 9/15: Newcastle United - Liverpool
Scraping 10/15: Fulham - Chelsea
Scraping 11/15: Crystal Palace - Manchester City
Scraping 12/15: Liverpool - Nottingham Forest
Scraping 13/15: Coventry - Hull
Scraping 14/15: Bournemouth - Everton
Scraping 15/15: Tottenham - Newcastle United
Inserted 15 fixtures

,match_id,date,home_team,away_team,h_id,a_id,home_goals,away_goals,home_xg,away_xg
0,31180,2026-08-21 19:00:00,Arsenal,Coventry,83,294,3,0,1.854240,0.558336
1,31181,2026-08-22 11:30:00,Hull,Manchester United,91,89,2,0,1.496270,1.778740
2,31182,2026-08-22 14:00:00,Everton,Crystal Palace,72,78,2,0,1.450850,2.230950
3,31183,2026-08-22 14:00:00,Ipswich,Sunderland,285,77,2,1,1.584520,1.177430
4,31184,2026-08-22 14:00:00,Nottingham Forest,Leeds,249,245,0,1,0.656681,0.466247
5,31185,2026-08-22 16:30:00,Brentford,Tottenham,244,82,3,0,4.041550,0.756284
6,31186,2026-08-23 13:00:00,Brighton,Aston Villa,220,71,4,0,4.003270,0.275249
7,31187,2026-08-23 13:00:00,Manchester City,Bournemouth,88,73,2,1,2.474440,0.707541
8,31188,2026-08-23 15:30:00,Newcastle United,Liverpool,86,87,2,2,1.594650,3.131330
9,31189,2026-08-24 19:00:00,Fulham,Chelsea,228,80,2,3,1.417070,2.583840
10,31190,2026-08-28 19:00:00,Crystal Palace,Manchester City,78,88,1,4,0.926624,2.566620
11,31191,2026-08-29 11:30:00,Liverpool,Nottingham Forest,87,249,2,2,1.279210,2.879370
12,31192,2026-08-29 14:00:00,Coventry,Hull,294,91,0,1,1.182330,0.459726
13,31193,2026-08-29 14:00:00,Bournemouth,Everton,73,72,1,1,2.258030,1.663520
14,31194,2026-08-29 16:30:00,Tottenham,Newcastle United,82,86,0,2,1.120370,1.009520